### PR TITLE
Cease and Desist

### PR DESCRIPTION
**Pull request by ISU-DSO**
Cease and Desist

### CODE REVIEW

**Comment by csteamengine** [comment]
Sorry I did not think about this as a sharing it for someone else, can I make is a private repo? Or do i just have to delete it?

**Comment by ISU-DSO** [comment]
A private repository will suffice. It is past the deadline and thus is acceptable now.

**Comment by csteamengine** [comment]
Ok. Sorry, I totally forgot that others could view it. Thank you for the
warning, is there any steps that need to be taken by me now?

On Mon, Nov 30, 2015 at 8:24 PM, ISU DSO notifications@github.com wrote:

> A private repository will suffice. It is past the deadline and thus is
> acceptable now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/csteamengine/ComSci228/pull/3#issuecomment-160827442.

## 

Gregory Steenhagen
Junior - Software Engineering
Iowa State University

**Comment by ISU-DSO** [comment]
If you wish to push further code before future deadlines, please make this repository private. As a student you have access to private repositories for [free](https://education.github.com/).

**Pull request merged**
